name: Deploy Spring Boot API

on:
  push:
    branches:
      - main   # Cambia si tu rama principal tiene otro nombre

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar y desplegar
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/RadioIsotop_API/radioisotopo
            git pull origin main
            mvn clean package -DskipTests
            sudo systemctl restart api
